[root@prometheus sql_exporter-0.5.linux-amd64]# cat sql_exporter9499.yml |grep -v ^" *#"
global:
  scrape_timeout_offset: 500ms
  min_interval: 0s
  max_connections: 30
  max_idle_connections: 30

target:
  data_source_name: 'sqlserver://ep_xxx02:epxxxxx88@10.8.x.xx:1433/?encrypt=disable'

  collectors: [mssql_standard,mssql_jf]

collector_files:
  - "*.collector.yml"
