[root@prometheus sql_exporter-0.5.linux-amd64]# cat sql_exporter.yml|grep -v ^.*#|grep -v ^$
global:
  scrape_timeout_offset: 500ms
  min_interval: 0s
  max_connections: 30
  max_idle_connections: 30
target:
  data_source_name: 'sqlserver://ep_auditxxxx2:eplxxxx88@10.x.x.xx:1433/?encrypt=disable'
  collectors: [mssql_standard,mssql_jf]
collector_files:
  - "*.collector.yml"
