[root@prometheus sql_exporter-0.5.linux-amd64]# cat xxx.collector.yml |grep -v ^$|grep -v ^#
collector_name: mssql_jf
metrics:
  - metric_name: jf1
    type: gauge
    help: 'xxxxxxxxxxxxxxxxxxxxxxxxx.'
    values: [xxxmem]
    query: |
      select physical_memory_in_use_kb as xxxmem from sys.dm_os_process_memory
  - metric_name: mssql_db_size
    type: gauge
    help: 'yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyySize of db.'
    key_labels:
      - db
    values: [size_mb]
    query: |
      select db.name as db,mf.size*8/1024 as size_mb
      from sys.databases db
      inner join sys.master_files mf on db.database_id=mf.database_id

  - metric_name: mssql_log_size
    type: gauge
    help: 'zzzzzzzzzzzzzzzzzzSize of db_log.'
    key_labels:
      - db
    values: [log_file]
    query: |
      SELECT instance_name AS db,
        --[Data File(s) Size (KB)]/1024 as datafile,
          [LOG File(s) Size (KB)]/1024 as log_file
        --[Log File(s) Used Size (KB)]/1024 as logfile_size
        --[Percent Log Used]
      FROM
        (
         SELECT *
         FROM sys.dm_os_performance_counters
         WHERE counter_name IN
        (
       'Data File(s) Size (KB)',
       'Log File(s) Size (KB)',
       'Log File(s) Used Size (KB)',
       'Percent Log Used'
        )
        AND instance_name != '_Total'
        ) AS Src
      PIVOT
        (
        MAX(cntr_value)
        FOR counter_name IN
        (
        [Data File(s) Size (KB)],
        [LOG File(s) Size (KB)],
        [Log File(s) Used Size (KB)],
        [Percent Log Used]
        )
        ) AS pvt
