groups:

- name: Mysql_alerts                   # 规则名称
  rules:
  - alert: 慢查询告警                    # 告警名称
    expr: rate(mysql_global_status_slow_queries{}[1m]) > 10  # 告警条件
    for: 1m                           # 持续时间
    labels:
      alertlevel: P1                  # 告警级别
    annotations:                      # 注释
      summary: "mysql最近一分钟的慢查询超过 10 条."    # 发送告警的内容
      description: '当前为 {{ $value }}.'

  - alert: 连接数告警
    expr: mysql_global_status_threads_connected{} > 2000
    for: 5m
    labels:
      alertlevel: P2
    annotations:
      summary: "mysql连接数已经超过2000."
      description: '当前连接数为 {{ $value }}.'


  - alert: 入流量告警
    expr: rate(mysql_global_status_bytes_received{}[5m])/1000000 > 2
    for: 5m
    labels:
      alertlevel: P1
    annotations:
      summary:  "mysql当前5分钟入网流量超过2M/s."
      description: '当前为 {{ $value | printf "%.2f" }}M.'

  - alert: 出流量告警
    expr: rate(mysql_global_status_bytes_sent{}[5m])/1000000 > 2
    for: 5m
    labels:
      alertlevel: P1
    annotations:
      summary: "mysql当前5分钟出网流量超过2M/s."
      description: '当前为 {{ $value | printf "%.2f" }}M.'


  - alert: Mysql告警
    expr: up{job="aly-mysql"} == 0
    for: 30s
    labels:
      alertlevel: P3
    annotations:
      summary: "mysql宕机了."
      description: '当前连接{{ $labels.instance }}数据库失败超过30s，请检查。'
