groups:

- name: Linux_alerts                   # 规则名称
  rules:
  - alert: CPU告警                    # 告警名称
    expr: 100-(avg(irate(node_cpu_seconds_total{mode="idle"}[5m])) by(instance)* 100) > 80  # 告警条件
    for: 10m                           # 持续时间
    labels:
      alertlevel: P0                  # 告警级别
    annotations:                      # 注释
      summary: "CPU使用率超过80%."    # 发送告警的内容
      description: '当前的CPU使用率为 {{ $value | printf "%.0f" }}%.'

  - alert: 内存告警
    expr: 100 -(node_memory_MemFree_bytes+node_memory_Buffers_bytes+node_memory_Cached_bytes ) / node_memory_MemTotal_bytes{instance!="47.100.126.11:9100"} * 100 > 90
    #expr: 100 -(node_memory_MemFree_bytes+node_memory_Buffers_bytes+node_memory_Cached_bytes ) / node_memory_MemTotal_bytes * 100 > 90
    for: 10m
    labels:
      alertlevel: P2
    annotations:
      summary: "内存使用率超过90%."
      description: '当前的内存使用率为 {{ $value | printf "%.0f" }}%.'


  - alert: 磁盘告警
    expr: 100-(node_filesystem_free_bytes{fstype=~"ext4|xfs"}/node_filesystem_size_bytes {fstype=~"ext4|xfs"}*100) > 80
    for: 5m
    labels:
      alertlevel: P1
    annotations:
      summary:  "{{$labels.mountpoint}}目录使用率超过了80%."
      description: '当前的使用率为 {{ $value | printf "%.0f" }}%.'

  - alert: 主机告警
    expr: up{job=~".*node.*"} == 0
    for: 10s
    labels:
      alertlevel: P3
    annotations:
      summary: "主机 {{ $labels.instance }} 可能挂了。"
      description: "主机 {{ $labels.instance }}已经10秒钟没有响应，请立即检查！"

